export const blogConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  POST_REQUEST: "POST_REQUEST",
  POST_SUCCESS: "POST_SUCCESS",
  POST_FAIL: "POST_FAIL",

  UPLOAD_REQUEST: "UPLOAD_REQUEST",
  UPLOAD_SUCCESS: "UPLOAD_SUCCESS",
  UPLOAD_FAIL: "UPLOAD_FAIL",

  FETCH_REQUEST: "FETCH_REQUEST",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAIL: "FETCH_FAIL",
};
