export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userContants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const productConstants = {
  PRODUCT_REQUEST: "PRODUCT_REQUEST",
  PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
  PRODUCT_FAIL: "PRODUCT_FAIL",
};

export const imageConstants = {
  UPLOAD_REQUEST: "UPLOAD_REQUEST",
  UPLOAD_SUCCESS: "UPLOAD_SUCCESS",
  UPLOAD_FAIL: "UPLOAD_FAIL",
};
